# Source: jxboot-helmfile-resources/templates/environments.yaml
apiVersion: jenkins.io/v1
kind: Environment
metadata:
  labels:
    env: "dev"
    team: jx
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: "dev"
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
spec:
  source:
    ref: "master"
    url: https://github.com/Tyagi0502/jx-cluster.git
  kind: Development
  label: Development
  namespace: jx
  promotionStrategy: "Never"
  webHookEngine: "Lighthouse"
  teamSettings:
    appsRepository: http://chartmuseum.jenkins-x.io
    defaultScheduler:
      apiVersion: jenkins.io/v1
      kind: Scheduler
      name: jx-meta-pipeline
    dockerRegistryOrg: ""
    envOrganisation: todo
    gitServer: https://github.com
    kubeProvider: "eks"
    pipelineUsername: "Tyagi0502"
    pipelineUserEmail: "jenkins-x@googlegroups.com"
    prowConfig: Scheduler
    storageLocations:
      - bucketUrl: s3://logs-jx-test-2021080910271651930000000a
        classifier: logs
      - bucketUrl: s3://reports-jx-test-20210809102713330700000006
        classifier: reports
