apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jx-test
    devEnvApprovers:
    - Tyagi0502
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "967882944490"
    provider: eks
    region: ap-south-1
    registry: 967882944490.dkr.ecr.ap-south-1.amazonaws.com
  environments:
  - key: dev
    owner: Tyagi0502
    repository: jx-cluster
  - key: staging
  - key: production
  ingress:
    domain: test.stylework.city
    externalDNS: true
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: abhishek@stylework.city
      enabled: true
      production: true
  pipelineUser:
    username: Tyagi0502
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-jx-test-20210809121553942100000009
  - name: reports
    url: s3://reports-jx-test-20210809121551114900000008
  - name: repository
    url: s3://repository-jx-test-20210809121551083900000002
  terraform: true
  vault:
    aws:
      dynamoDBRegion: ap-south-1
      dynamoDBTable: vault-unseal-jx-test-cunSpIrQ
      kmsKeyId: 76d9286f-43fb-44a9-b408-cae7e59ead73
      kmsRegion: ap-south-1
      s3Bucket: vault-unseal-jx-test-20210809121551102500000005
      s3Region: ap-south-1
  webhook: lighthouse
