filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: https://chartmuseum-jx.test.stylework.city
releases:
- chart: dev/node-test
  version: 0.0.1
  name: node-test
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
