# Source: acme/templates/cert-manager-prod-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-test-stylework-city-p"
  labels:
    jenkins.io/letsencrypt-service: production
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'acme-jx'
  namespace: jx
spec:
  secretName: "tls-test-stylework-city-p"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.test.stylework.city"
  dnsNames:
    - "*.test.stylework.city"
    - "test.stylework.city"
